# Generated by Django 5.0.7 on 2024-09-05 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_remove_workshopdatetime_time_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='date',
        ),
        migrations.AddField(
            model_name='workshopdatetime',
            name='location',
            field=models.CharField(default='school', max_length=255),
        ),
        migrations.AlterField(
            model_name='workshopdatetime',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workshops.workshop'),
        ),
    ]
