# Generated by Django 5.0.7 on 2024-09-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='80', max_digits=10),
        ),
    ]
